### ISSUE TITLE
Question about your usage of angularjs in the code

### ISSUE THREAD

**Issue by freeman42x** [Azkellas/cgenhancer#2]
How did you figure out how to get the scope without calling [angular.reloadWithDebugInfo()](https://docs.angularjs.org/api/ng/function/angular.reloadWithDebugInfo) first? Currently, they disabled the ability to access scopes from DOM elements so calling that function first is required.

I'm working on a Clash of Code usersript enhancer and being able to modify the angularjs scope and call updates would be ideal.

**Comment by Azkellas** [comment]
Hi,

This is done lines 66-73:

```
    if (useAgentModule)
    {
        // required to access codingame local api
        // done first before angular has time to load
        const ngDebugStr = 'NG_ENABLE_DEBUG_INFO!';
        if (unsafeWindow.name.indexOf(ngDebugStr) === -1)
            unsafeWindow.name = ngDebugStr + unsafeWindow.name;
    }
```

I didn't figure it out myself, I think this snippet comes from player_one's [CG Spunk](https://github.com/danBhentschel/CGSpunk).

This is still working on my side (although it should be noted that using the debug mode of angular makes the page slower).

**Comment by freeman42x** [comment]
@Azkellas Thank you very much, will give this a try. I think the slowing down from debug mode would be acceptable based on what I have seen from using `angular.reloadWithDebugInfo()`.
